### ISSUE TITLE
Найденные баги

### ISSUE THREAD

**Issue by xlabsoft** [DronB/mywebmavenproject#1]
1 принимает неверный - проблема валидации
вводим емейл (без@) и оно его прохавывает

2 когда заходишь под админом и нажимаешь "показать список юсеров" - не показывает список

3 когда нажимаешь "удалить юсера" - не удаляет его

**Comment by DronB** [comment]
1. Валидация ввода Email при регистрации добавлена 
2. При просмотре профайла админом, реализована возможность просмотра всех пользователей
3. Добавлена возможность удаления пользователей админом и пользователя самого себя

**Comment by xlabsoft** [comment]
1 Проблема валидации при входе

Ожидается:
формат ввода емейл вида name@mail.com
Видимый:
хавает емейл в любом формате, например: 1 - тоже счтается емелом

**Comment by xlabsoft** [comment]
2 Проблема с админской учеткой - "просмотр юсеров"

Ожидается:
Что под админом можно посмотреть список пользаователей
Видимый результат:
Не показывает список пользователей

**Comment by xlabsoft** [comment]
3 Проблема с админской учеткой - "удаление юсеров"

Ожидается:
Что под админом можно удалить пользаователя
Видимый результат:
Не удаляет пользователя
